### ISSUE TITLE
github Authorization callback URL

### ISSUE THREAD

**Issue by tashi12** [manjurulhoque/django-job-portal#21]
hello sir,
 what is the Authorization callback URL here

**Comment by dincerunal** [comment]
Hi ,

You can view this url  [https://github.community/t/what-is-user-authorization-callback-url-for/13990](url) 

bets regards

**Comment by manjurulhoque** [comment]
![image](https://user-images.githubusercontent.com/15651792/119820518-5f5ac480-bf13-11eb-979e-099f85bb40bd.png)
