### ISSUE TITLE
Application callback url  in github devlopers side...

### ISSUE THREAD

**Issue by tashi12** [manjurulhoque/django-job-portal#22]
Hello,
Kindly please tell me what is the github application  callback url on developers side...
Thanks!!

**Comment by manjurulhoque** [comment]
Callback URL is http://127.0.0.1:8000/. 
![image](https://user-images.githubusercontent.com/15651792/119820282-1dca1980-bf13-11eb-8f15-8ee2a773ce4d.png)

**Comment by tashi12** [comment]
Hello sir, 
I used the same url........but after that its showing error given below in image--

[
![errorurl](https://user-images.githubusercontent.com/78637956/120132858-b4832880-c1e8-11eb-8d6f-2ae5e9d324fe.PNG)
](url)
