### ISSUE TITLE
Can't load initial data and can't create any tags from Django admin.

### ISSUE THREAD

**Issue by enjoysmath** [manjurulhoque/django-job-portal#44]
The line in the instructions about loading initial data seems wrong because there is no fixtures/ directory within the project.

I tried adding in "Python" / "C++" as Tags in the django admin panel and they don't show up when an employer goes to create a job (so the job form cannot be completed/submitted).

All I need is for Tags to work, not the intial data.  I am going to start over fresh with your repository's code.

**Comment by manjurulhoque** [comment]
Is this issue still valid?

**Comment by manjurulhoque** [comment]
I am sure it's working.
