### ISSUE TITLE
Some Problems

### ISSUE THREAD

**Issue by ramazanguven** [manjurulhoque/django-job-portal#5]
Hi Manjurul,
Firstly thanks for sharing this work.
I have some problems and I want to ask to you because I'm new at Django.

I am using Django v2.2 and Python 3.6
1-) I get an error when add post a new job
2-) Other error when I click on a filled session at Dashboard -->[ Mark as Filled ] session

Are these general problems or just me?
Thanks

**Comment by manjurulhoque** [comment]
1 is solved by disabling register_document to the elasticsearch.
