### ISSUE TITLE
Add vacancy field in job model

### ISSUE THREAD

**Issue by manjurulhoque** [manjurulhoque/django-job-portal#60]
Also, update form fields when creating or updating job

**Comment by rezwan2525** [comment]
I can work on this task. Could you please assign this to me ? Also do you any design plan in mind, in which place are we going to put "Vacancy" field ?

**Comment by manjurulhoque** [comment]
You could add it with the Category input field.

**Comment by manjurulhoque** [comment]
@rezwan2525 Are you doing this or not?

**Comment by rezwan2525** [comment]
@manjurulhoque sure, I am going to do it asap.

**Comment by rezwan2525** [comment]
@manjurulhoque If we add the vacancy field above the category field, is it okay? Please let me know your feedback.
![create_job](https://user-images.githubusercontent.com/30120066/196047877-62e4eef9-1f42-4e10-9c1e-fd0ed07c3fe5.jpg)

( minimum value = 1 for the vacancy field)

**Comment by manjurulhoque** [comment]
Make col-md-6 for category and col-md-6 for vacancy field.

**Comment by rezwan2525** [comment]
@manjurulhoque Can we show the "vacancy" on the job detail page this way?
![Screenshot_1](https://user-images.githubusercontent.com/30120066/196049872-a768f8e2-bc02-419f-8bd1-80784a303621.jpg)

**Comment by manjurulhoque** [comment]
Yes, that would be good. Also show in the dashboard

**Comment by rezwan2525** [comment]
Did you mean all jobs page? or employers' job dashboard page?

**Comment by rezwan2525** [comment]
There are already 6 columns there. What do you think is the best fit to show "vacancy" field?
![image](https://user-images.githubusercontent.com/30120066/196071029-8283d4d5-0c33-49ec-878c-098b1a1d5288.png)
