### ISSUE TITLE
Found number of jobs only shows the current pages job number

### ISSUE THREAD

**Issue by rezwan2525** [manjurulhoque/django-job-portal#63]
**Checklist**
- [x] I have verified that that issue exists against the `master` branch.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have reduced the issue to the simplest possible case.

**Describe the bug**
When we open all job list pages, we can see "found jobs" only for the current page. 

**To Reproduce**
1. Go to the job list page
2. Observe the found job number
3. Go to the next page
4. See the job numbers

**Expected behavior**
The job list page should show the total number of jobs found.

**Screenshots**
![image](https://user-images.githubusercontent.com/30120066/196050394-74bcdc92-b8d4-4d94-9fdf-cd7954c07d1f.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by manjurulhoque** [comment]
Fixed. Thank you!
