### ISSUE TITLE
Shows "403 forbidden" page when try to apply with employer account

### ISSUE THREAD

**Issue by rezwan2525** [manjurulhoque/django-job-portal#64]
**Checklist**
- [x] I have verified that that issue exists against the `master` branch.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] I have reduced the issue to the simplest possible case.

**Describe the bug**
Shows "403 forbidden" page when try to apply with employer account

**To Reproduce**
1. Go to any job details page
2. Click on 'Apply for this job' button

**Expected behavior**
The "Apply for this job" button can be disabled or hidden for the employer account

**Screenshots**
the apply button
![image](https://user-images.githubusercontent.com/30120066/196050639-19fe1c0f-520d-472d-9673-1645edf5ea91.png)
the forbidden page
![image](https://user-images.githubusercontent.com/30120066/196050665-cf731e75-0627-4fca-962f-88a5940926f5.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome

**Comment by manjurulhoque** [comment]
Can employers apply for the job?

**Comment by rezwan2525** [comment]
No, but they can click on "Apply for the job" button which leads to a forbidden page.

**Comment by manjurulhoque** [comment]
Fixed now. Thanks for the report
