### ISSUE TITLE
Couldn't find default admin credentials

### ISSUE THREAD

**Issue by shanujha** [manjurulhoque/django-job-portal#75]
**Checklist**

- [ x ] I have verified that that issue exists against the `master` branch.
- [ x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x ] I have reduced the issue to the simplest possible case.

**Describe the bug**
I might be blind, so help me with this. I couldn't find the default admin credentials anywhere.
I tried opening the sqlite file in notepad, but the max anything i could find was admin@admin.com (one of the users)
I don't really have expertise in database, to I wondered, if anyone is able to use this application, you could guide me towards where I could find the default admin credentials, or if they even exist?

If someone, comments, I could open a PR to add the creds in the Readme file

**Specify the team with the correct label**
enhancement

**Expected behavior**
Could you help me, I can create PR to add the default credentials in the Readme.md

**Comment by manjurulhoque** [comment]
Thank you for raising the issue.

**Comment by Pavankumardontha** [comment]
@manjurulhoque can you please check my PR raised for this issue ?
